In [ ]:
import numpy as np

# one dimensional array 

In [ ]:
l1=[1,2,3,4]
l1

[1, 2, 3, 4]

In [ ]:
n1=np.array(l1)
n1

array([1, 2, 3, 4])

In [ ]:
#Multi dimensional array


l2=[6,7,8,9,10,1]
l2

[6, 7, 8, 9, 10, 1]

In [ ]:
l3=np.array([[l1],[l2]])

In [ ]:
l3

array([[list([1, 2, 3, 4])],
       [list([6, 7, 8, 9, 10, 11])]], dtype=object)

In [ ]:
type(l3)

numpy.ndarray

In [ ]:
#numpy as using the zero value 

import numpy as np

np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#arrange method

n=np.arange(1,10)

In [ ]:
n

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# arange the array with respect x and y and intervals is z

#odd value and even value

np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
#even value 

np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [ ]:
# arange the z number  between x and y

In [ ]:
np.linspace(10,20,10)

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [ ]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [ ]:
#filling the same no in x and y
#using the full method 

np.full((5,5),10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [ ]:
#random method 

#filling the random value in x and y

In [ ]:
np.random.randint(100,200,10)

array([184, 161, 184, 151, 117, 139, 155, 179, 100, 131])

In [ ]:
##INSPECTING A NUMPY ARRAY

import numpy as np

l3=np.array([[l1],[l2]])

In [ ]:
l3

array([[list([1, 2, 3, 4])],
       [list([6, 7, 8, 9, 10, 1])]], dtype=object)

In [ ]:
np.shape(l3)

(2, 1)

In [ ]:
l1=[1,2,3,4]

In [ ]:
l2=[5,5,5,5,5,5]

In [ ]:
n=np.array([[1,2,3,4],[5,5,5,5]])
n

array([[1, 2, 3, 4],
       [5, 5, 5, 5]])

In [ ]:
n.shape


(2, 4)

In [ ]:
n

array([[1, 2, 3, 4],
       [5, 5, 5, 5]])

In [ ]:
n

array([[1, 2, 3, 4],
       [5, 5, 5, 5]])

In [ ]:

a=np.arange(24)


In [ ]:
a.ndim

1

In [ ]:
b=a.reshape(12,2)  #trick is that calculate the factor 24:1,2,3,4,6,8,12,24
b

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [ ]:
#sind the no of array element in array

a.size

24

In [ ]:
#find the data type of the array

a=np.arange(24,dtype=float)

In [ ]:
print(a.dtype)
a

float64


array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.])

In [ ]:
 #PERFORMING MATHEMATICAL FUNCTIONS USING NUMPY

In [ ]:
#Addtion
#Subtraction
#multiplication
#Divide


# some other mathmatical function

log
exponencial
sin
cos 


In [ ]:
#Addtion


In [ ]:
l1=[2,4,6]
l2=[1,3,5,]

In [ ]:
import numpy as np
#when we need the two array value  in seprate 

In [ ]:
np.sum([[2,4,6],[1,3,5,]],axis=0)

array([ 3,  7, 11])

In [ ]:

#sum of the function with puting axis =1

np.sum([[2,4,6],[1,3,5,]],axis=1)

array([12,  9])

In [ ]:
#Subtraction

np.subtract(30,20)

10

In [ ]:
#multiplication


np.multiply(20,30)

600

In [ ]:
#divide 

In [ ]:

np.divide(30,20)

1.5

In [ ]:


l1

[2, 4, 6]

In [ ]:
l2

[1, 3, 5]

In [ ]:
np.multiply([2,4,6],[1,3,5,])



array([ 2, 12, 30])

In [ ]:
np.divide([2,4,6],[1,3,5,])

array([2.        , 1.33333333, 1.2       ])

In [ ]:
print(np.exp(l1))
print(np.cos(l1))
print(np.sin(l1))
print(np.log(l1))

[  7.3890561   54.59815003 403.42879349]
[-0.41614684 -0.65364362  0.96017029]
[ 0.90929743 -0.7568025  -0.2794155 ]
[0.69314718 1.38629436 1.79175947]


In [ ]:
print(np.exp(l2))
print(np.cos(l2))
print(np.sin(l2))
print(np.log(l2))

[  2.71828183  20.08553692 148.4131591 ]
[ 0.54030231 -0.9899925   0.28366219]
[ 0.84147098  0.14112001 -0.95892427]
[0.         1.09861229 1.60943791]


In [ ]:
l1

[2, 4, 6]

In [ ]:
l2

[1, 3, 5]

In [ ]:
#comparison of the elemet 

np.equal(l1,l2)

array([False, False, False])

In [ ]:
#comparison of the array

In [ ]:
np.array_equal(l1,l2)

False

In [ ]:
l1

[2, 4, 6]

In [ ]:
l2

[1, 3, 5]

In [ ]:
l3=[10,20,30]
l3

[10, 20, 30]

In [ ]:
# aggregate function

#array wise sum
#min of an array
#means of the array
#median of the array
#correlation of the array
#standard deviation of the array


In [ ]:
#array wise sum

import numpy as np

In [ ]:
#L1
print(np.sum(l1))
print(np.min(l1))
print(np.mean(l1))
print(np.median(l1))
print(np.corrcoef(l1))
print(np.std(l1))

12
2
4.0
4.0
1.0
1.632993161855452


In [ ]:
l2

[1, 3, 5]

In [ ]:
#L2
l2=[1, 3, 5]


In [ ]:
l2

[1, 3, 5]

In [ ]:

print(np.sum(l2))
print(np.min(l2))
print(np.mean(l2))
print(np.median(l2))
print(np.corrcoef(l2))
print(np.std(l2))

9
1
3.0
3.0
1.0
1.632993161855452


# Array comparison

In [ ]:
#element wise comparison

a=[1,2,4]
b=[1,2,3]
c=[1,2,4]

np.equal(a,b)


array([ True,  True, False])

In [ ]:
np.equal(a,c)

array([ True,  True,  True])

In [ ]:
#array wise comparison

a=[1,2,4]
b=[1,2,3]
c=[1,2,4]

In [ ]:
a

[1, 2, 4]

In [ ]:
b

[1, 2, 3]

In [ ]:
c

[1, 2, 4]

In [ ]:
np.array_equal(a,b)

False

In [ ]:
np.array_equal(a,c)

True

In [ ]:
#aggregate THE FUNTION WITH VALUE 


print(np.sum(a))
print(np.min(a))
print(np.mean(a))
print(np.median(a))
print(np.corrcoef(a))
print(np.std(a))

7
1
2.3333333333333335
2.0
1.0
1.247219128924647


In [ ]:
#CONCEPT OF THE BRODCATINGS IN GIVEN FUNCTIONS

a=np.array([[0,0,0],[2,4,6],[1,3,5,],[4,5,6]])


In [ ]:
a

array([[0, 0, 0],
       [2, 4, 6],
       [1, 3, 5],
       [4, 5, 6]])

In [ ]:
b=np.array([[3,4,5]])

In [ ]:
b

array([[3, 4, 5]])

In [ ]:
c=a+b

In [ ]:
c

array([[ 3,  4,  5],
       [ 5,  8, 11],
       [ 4,  7, 10],
       [ 7,  9, 11]])

In [ ]:
#second way to write 

a=np.array([[0,0,0],[2,4,6],[1,3,5,],[4,5,6]])
b=np.array([[3,4,5]])
print("First Array:\n",a,'\n')
print("Second Array:\n",b,'\n')
print("First Array+Second Array:\n",a+b,'\n')

First Array:
 [[0 0 0]
 [2 4 6]
 [1 3 5]
 [4 5 6]] 

Second Array:
 [[3 4 5]] 

First Array+Second Array:
 [[ 3  4  5]
 [ 5  8 11]
 [ 4  7 10]
 [ 7  9 11]] 



In [ ]:
#ARRAY multiplication

l1

[2, 4, 6]

In [ ]:
l2

[1, 3, 5]

In [ ]:
#concatenate two array

np.concatenate((l1,l2))

array([2, 4, 6, 1, 3, 5])

In [ ]:
#stack array row wise:   vertically 

np.vstack((l1,l2))

array([[2, 4, 6],
       [1, 3, 5]])

In [ ]:
##stack array row wise:   horizontally 

np.hstack((l1,l2))


array([2, 4, 6, 1, 3, 5])

In [ ]:
#stack array column wise:

np.column_stack((l1,l2))

array([[2, 1],
       [4, 3],
       [6, 5]])

In [ ]:
#split array 

x=np.arange(16.0).reshape(4,4)


In [ ]:
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [ ]:
#split array 

np.hsplit(x,2)


[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]),
 array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

In [ ]:
np.hsplit(x,[3,6])

[array([[ 0.,  1.,  2.],
        [ 4.,  5.,  6.],
        [ 8.,  9., 10.],
        [12., 13., 14.]]),
 array([[ 3.],
        [ 7.],
        [11.],
        [15.]]),
 array([], shape=(4, 0), dtype=float64)]

# INDEXING AND SLICING USING NUMPY

In [ ]:
a=['m','o','n','d','a','y']
a

['m', 'o', 'n', 'd', 'a', 'y']

In [ ]:
#last value  extracted

a[-1]

'y'

In [ ]:

#assign the value 
a[-1]=5



In [ ]:
a

['m', 'o', 'n', 'd', 'a', 5]

In [ ]:
#frnt of the  index value 
#just before value a

a[:1]

['m']

In [ ]:
#remove the index 
a[1:]

['o', 'n', 'd', 'a', 5]

In [ ]:
#range of the value 
a[1:4]

['o', 'n', 'd']

In [ ]:
a[1]='satyam'

In [ ]:
a

['m', 'satyam', 'n', 'd', 'a', 5]

In [ ]:
a=np.array([[0,0,0],[2,4,6],[1,3,5,],[4,5,6]])

In [ ]:
a

array([[0, 0, 0],
       [2, 4, 6],
       [1, 3, 5],
       [4, 5, 6]])

In [ ]:
#extract the first array 

a[0]


array([0, 0, 0])

In [ ]:
a[:1]

array([[0, 0, 0]])

In [ ]:
a[:1,1:]

array([[0, 0]])

In [ ]:
a[:2]

array([[0, 0, 0],
       [2, 4, 6]])

In [ ]:
a[:2,1:]

array([[0, 0],
       [4, 6]])

# Advantage of the numpy  list 

In [ ]:
#numpy vs list: Memory size 

import numpy as np
import sys
#define a  list 

l=range(1000)
print("size of the list:",sys.getsizeof(1)*len(l))


#define the array
a=np.arange(1000)
print("size of an array:",a.size*a.itemsize)



size of the list: 28000
size of an array: 4000


In [ ]:

#scipy #it is scientific calculation  of the library 

scipy.cluster   #it is used for vector size of the calculation
scipy.stats      #it is used for statistics
scipy.optimize   #it is used for optimization (max and min the function)
scipy.integrate  #it is used for integration of the fuction 
scipy.linalg      #it is used for the linear alzebra of the function 
scipy.fftpack    #it is used for the fftpack of the function 
scipy.signal     #it is used for the signal processing of the function

NameError: name 'scipy' is not defined

In [ ]:
scipy.cluster 

NameError: name 'scipy' is not defined

In [ ]:
import numpy as np
import pandas as pd


In [ ]:
car=pd.read_csv('panda\mtcars2.csv')
car

S.No           Unnamed: 1   mpg  cyl   disp   hp  drat     wt   qsec  vs  \
0      1            Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   
1      2        Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   
2      3           Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   
3      4       Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   
4      5    Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   
5      6              Valiant  18.1    6  225.0  105  2.76  3.460    NaN   1   
6      7           Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   
7      8            Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   
8      9             Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   
9     10             Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   
10    11            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   
11    12           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   
12    13           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   
13    14          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   
14    15   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   
15    16  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   
16    17    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   
17    18             Fiat 128  32.4    4   78.7   66  4.08  2.200    NaN   1   
18    19          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   
19    20       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   
20    21        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   
21    22     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   
22    23          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   
23    24           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   
24    25     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   
25    26            Fiat X1-9  27.3    4   79.0   66  4.08  1.935    NaN   1   
26    27        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   
27    28         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   
28    29       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   
29    30         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   
30    31        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   
31    32           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   

    am  gear  carb  
0    1     4     4  
1    1     4     4  
2    1     4     1  
3    0     3     1  
4    0     3     2  
5    0     3     1  
6    0     3     4  
7    0     4     2  
8    0     4     2  
9    0     4     4  
10   0     4     4  
11   0     3     3  
12   0     3     3  
13   0     3     3  
14   0     3     4  
15   0     3     4  
16   0     3     4  
17   1     4     1  
18   1     4     2  
19   1     4     1  
20   0     3     1  
21   0     3     2  
22   0     3     2  
23   0     3     4  
24   0     3     2  
25   1     4     1  
26   1     5     2  
27   1     5     2  
28   1     5     4  
29   1     5     6  
30   1     5     8  
31   1     4     2

In [ ]:
car.drop(columns=["S.No","Unnamed: 1"])

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0   21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1   21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2   22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3   21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4   18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2
5   18.1    6  225.0  105  2.76  3.460    NaN   1   0     3     1
6   14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4
7   24.4    4  146.7   62  3.69  3.190  20.00   1   0     4     2
8   22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2
9   19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4
10  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4
11  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3     3
12  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3     3
13  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3     3
14  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3     4
15  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3     4
16  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3     4
17  32.4    4   78.7   66  4.08  2.200    NaN   1   1     4     1
18  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4     2
19  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4     1
20  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3     1
21  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3     2
22  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3     2
23  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3     4
24  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3     2
25  27.3    4   79.0   66  4.08  1.935    NaN   1   1     4     1
26  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5     2
27  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5     2
28  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5     4
29  19.7    6  145.0  175  3.62  2.770  15.50   0   1     5     6
30  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5     8
31  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4     2

In [ ]:
from scipy.cluster.vq import kmeans,vq,
centroid,_=kmeans(data,3)
idx,_=vq(data,centroid)
idx

SyntaxError: trailing comma not allowed without surrounding parentheses (<ipython-input-23-ebc4f544e454>, line 1)